site_name: My DevOps Interview Preparation
repo_name: devops-interview-preparation
repo_url: https://github.com/alelapi/devops-interview-preparation
site_description: "My DevOps Interview Preparation"
site_author: Alessio Lapi
site_url: ''

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        primary: custom
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.path
    - navigation.footer

extra_css:
  - 'assets/css/app.css'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - smarty
  - footnotes
  - meta
  - toc:
      permalink: true
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - tables

plugins:
  - search
  - drawio_file

nav:
  - Home: index.md
  - AWS:
    - Computing:
      - aws/computing/amplify.md
      - aws/computing/api_gateway.md
      - aws/computing/autoscaling_groups.md
      - aws/computing/ec2.md
      - aws/computing/ecs.md
      - aws/computing/elastic_beanstalk.md
      - aws/computing/elb.md
      - aws/computing/lambda.md
    - Databases:
      - aws/database/athena.md
      - aws/database/aurora.md
      - aws/database/dynamodb.md
      - aws/database/elasticache.md
      - aws/database/rds.md
    - Management:
      - aws/management/appconfig.md
      - aws/management/billing.md
      - aws/management/cloudformation.md
      - aws/management/sam.md
      - aws/management/ssm.md
    - Messaging:
      - aws/messaging/firehose.md
      - aws/messaging/kinesis_data_analytics.md
      - aws/messaging/kinesis_data_streams.md
      - aws/messaging/ses.md
      - aws/messaging/sns.md
      - aws/messaging/sqs.md
    - Monitoring:
      - aws/monitoring/cloudtrail.md
      - aws/monitoring/cloudwatch.md
      - aws/monitoring/eventbridge.md
      - aws/monitoring/xray.md
    - Network:
      - aws/network/cloudfront.md
      - aws/network/elb.md
      - aws/network/route53.md
      - aws/network/vpc.md
    - Security & Identity:
      - aws/security/cognito.md
      - aws/security/iam.md
      - aws/security/inspector.md
      - aws/security/kms.md
      - aws/security/macie.md
      - aws/security/secrets_manager.md
      - aws/security/shield.md
      - aws/security/sso.md
    - Storage:
      - aws/storage/ebs.md
      - aws/storage/efs.md
      - aws/storage/s3.md
    - Tools:
      - aws/tools/cloud9.md
      - aws/tools/codeartifact.md
      - aws/tools/codebuild.md
      - aws/tools/codecommit.md
      - aws/tools/codedeploy.md
      - aws/tools/codeguru.md
      - aws/tools/codepipeline.md
    - aws/appsync.md
    - aws/cdk.md
    - aws/cloudhsm.md
    - aws/codestar.md
    - aws/sar.md
    - aws/step_function.md
    - aws/sts.md
    - aws/swf.md
    - aws/trusted_advisor.md
  - GCP:
    - Networking:
      - gcp/networking/bgp.md
      - gcp/networking/cloud-router.md
      - gcp/networking/hybrid-connectivity.md
      - gcp/networking/iam-roles.md
      - gcp/networking/load-balancing.md
      - gcp/networking/shared-vpc.md
      - gcp/networking/vpc-peering.md
    - Kubernetes:
      - gcp/kubernetes/gke-overview.md
      - gcp/kubernetes/cluster-types.md
      - gcp/kubernetes/scaling.md
      - gcp/kubernetes/service-mesh-istio.md

  - Kubernetes:
    - kubernetes/envoy.md
    - kubernetes/kubernetes_serverless_platforms.md
    - kubernetes/pod_security_admission.md
    - kubernetes/admission_controller.md
    - kubernetes/pod_priority_and_preemption.md
    - kubernetes/aggregation_layer.md
    - kubernetes/encryptionconfig.md
    - kubernetes/submariner.md
    - kubernetes/kubefed.md
    - kubernetes/pod_disruption_budget.md
    - kubernetes/observability_tools.md
    - kubernetes/endpoint.md
    - kubernetes/cilium.md
    - Open Standards:
      - kubernetes/open_standards/open_standards.md
      - kubernetes/open_standards/cni_components.md
      - kubernetes/open_standards/cpi_components.md
      - SMI:
        - kubernetes/open_standards/SMI/what_is_a_service_mesh.md
        - kubernetes/open_standards/SMI/istio.md
        - kubernetes/open_standards/SMI/linkerd.md
        - kubernetes/open_standards/SMI/description.md
    - CKA:
      - kubernetes/cka/etcd.md
      - kubernetes/cka/vpa.md
      - kubernetes/cka/kubelet_issues.md
      - kubernetes/cka/utilities.md
      - kubernetes/cka/openssl.md
      - kubernetes/cka/helm.md
      - kubernetes/cka/cri.md
      - kubernetes/cka/jsonpath.md
    - KCSA:
      - kubernetes/kcsa/compliance_frameworks.md
      - kubernetes/kcsa/compliance_security_frameworks_tools.md
      - kubernetes/kcsa/kubernetes_auditing_policy.md
      - kubernetes/kcsa/linux_tools.md
      - kubernetes/kcsa/security_context.md
      - kubernetes/kcsa/threat_modeling_frameworks.md
      - kubernetes/kcsa/virtualizers.md
    - CKS:
      - kubernetes/cks/k8s_dashboard.md
      - kubernetes/cks/cert_auth.md
      - kubernetes/cks/apparmor.md
      - kubernetes/cks/falco.md
      - kubernetes/cks/seccomp.md
      - kubernetes/cks/image_scanning.md
      - kubernetes/cks/kube_bench.md
      - kubernetes/cks/audit_logging.md
      - kubernetes/cks/admission_controller_config.md
      - kubernetes/cks/cilium.md
      - kubernetes/cks/secure_docker_daemon.md
      - kubernetes/cks/istio_mtls.md
      - kubernetes/cks/opa.md
      - kubernetes/cks/runtimeclass.md
      - Exercises:
        - kubernetes/cks/exercises/falco-rule.md
        - kubernetes/cks/exercises/use-sbom.md
        - kubernetes/cks/exercises/istio-mtls.md
        - kubernetes/cks/exercises/docker-socket-security.md
        - kubernetes/cks/exercises/hostpath-only.md
        - kubernetes/cks/exercises/p2p-encryption-istio-cilium.md
        - kubernetes/cks/exercises/pod-security-standards.md
        - kubernetes/cks/exercises/cilium.md
        - kubernetes/cks/exercises/update-kubelet-config.md
        - kubernetes/cks/exercises/security-static-analysis.md
  - Architectural Patterns:
    - architectural-patterns/bulkhead.md
    - architectural-patterns/circuit_breaker.md
    - architectural-patterns/event_driven.md
    - architectural-patterns/event_sourcing.md
    - architectural-patterns/saga_pattern.md
    - architectural-patterns/strangler.md
  - General:
    - general/different_types_of_scaling.md
  - Linux:
    - Storage:
      - linux/storage/lvm-storage.md
      - linux/storage/virtual-file-system.md
      - linux/storage/filesystems.md
      - linux/storage/remote-filesystems.md
      - linux/storage/swap-space.md
      - linux/storage/automounters.md
      - linux/storage/storage-performance.md
    - Network:
      - linux/network/ipv4-ipv6-hostname.md
      - linux/network/time-synchronization.md
      - linux/network/monitor-troubleshoot-networking.md
      - linux/network/openssh-configuration.md
      - linux/network/packet-filtering-nat.md
      - linux/network/static-routing.md
      - linux/network/bridge-bonding.md
      - linux/network/reverse-proxy-load-balancer.md

